name: Linux branch build

# Disable for now until we are going to release a linux artifact
on:
  push:
    branches:
      - 'never'

env:
  JAVA_HOME: /home/runner/jdk
  GRAALVM_HOME: /home/runner/jdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "gluonhq/graal"
          tag: "gluon-22.1.0.1-Final"
          fileName: "*java17-linux-gluon*.tar.gz"
      - name: Extract JDK
        run: |
          mkdir -p $JAVA_HOME
          tar -xzf *java17-linux-gluon*.tar.gz -C $JAVA_HOME --strip-components=1
      - name: Install libraries
        run: |
          sudo apt update && sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          save-always: true
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw -B clean install
      - name: Create tag
        run: |
          git tag -f latest_build
          git push -f origin latest_build
#      - name: Build native
#        run: ./mvnw gluonfx:build -f sdkman-ui
