name: Windows branch build

on:
  push:
    tags:
      - '**'
  release:
    types: [created]

env:
  JAVA_HOME: D:\a\sdkman-ui\sdkman-ui\jdk
  GRAALVM_HOME: D:\a\sdkman-ui\sdkman-ui\jdk
  gluon_version: 22.1.0.1-Final

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1
      - uses: robinraju/release-downloader@v1.10
        with:
          repository: "gluonhq/graal"
          tag: "gluon-${{ env.gluon_version }}"
          fileName: "*java17-windows-gluon-*.zip"
      - name: Extract JDK
        run: |
          unzip graalvm-svm-java17-windows-gluon-${{ env.gluon_version }}.zip
          Rename-Item -path "graalvm-svm-java17-windows-gluon-${{ env.gluon_version }}" jdk
      - name: Make staging directory
        run: mkdir staging

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          save-always: true
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw -B clean install -DskipTests
      - name: Build native
        run: ./mvnw gluonfx:build -f sdkman-ui
      - name: Assamble zip
        run: |
          ./mvnw org.apache.maven.plugins:maven-assembly-plugin:single@assemble-windows -f sdkman-ui