name: Linux branch build

on:
  push:
    branches:
      - '**'

env:
  JAVA_HOME: /home/runner/jdk
  GRAALVM_HOME: /home/runner/jdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          save-always: true
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: ./mvnw -B clean verify
      - name: Create tag
        # Only on main
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -f latest_build
          git push -f origin latest_build
#      - name: Build native
#        run: ./mvnw gluonfx:build -f sdkman-ui
