name: Branch build
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: "Build ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache skdman binaries
        id: cache-sdkman
        uses: actions/cache@v4
        env:
          cache-name: cache-skdman
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.sdkman
          save-always: true
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/.sdkmanrc') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Java ${{ matrix.version }}
        id: sdkman
        uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
      - name: Verify Java ${{ matrix.version }}
        run: ./mvnw -version